name: Neon GitHub Action template
description: Neon GitHub Action template
author: Neon Database
branding:
  icon: align-left
  color: green
inputs:
  api_key:
    description: The Neon API key
    required: true
  api_host:
    description: The Neon API Host
    default: https://console.neon.tech/api/v2
outputs:
  projects:
    description: The list of projects in your Neon account
runs:
  using: node20
  main: dist/index.js
